### ISSUE TITLE
Visual Correspondence Matching

### ISSUE THREAD

**Issue by reynoldscem** [KU-CVLAB/NeMF#1]
Hi,

Enjoyed looking over the paper. I was wondering if you could comment at all on the suitability of this work for visual (rather than semantic) correspondence matching? I.e. For use in an image stitching, or structure-from-motion context.

**Comment by SunghwanHong** [comment]
Thanks for your interest in our work! 

We are planning to extend this work to include evaluation on more general matching (but not limited to) benchmarks and provide more analysis. 

As an additional comment, while I was working on this project, I observed its feasibility to other cost volume using tasks (but just that we did not attain SOTA, which i assume hyperparameters or some settings should be tuned for better performance). This means that in its current form, I am not sure if NeMF can have better performance than other SOTA works.
