### ISSUE TITLE
Possible bug in utils_training/evaluation.py

### ISSUE THREAD

**Issue by JunbongJang** [KU-CVLAB/NeMF#4]
I implemented the training code myself, but my trained model yielded PCK less than 10 at the threshold 0.1.
Then, I found that the function, eval_kps_transfer_test() is using source keypoints as ground truth instead of target keypoints.
After the fix, I get a PCK of about 42 at the threshold 0.1

Inside the function eval_kps_transfer_test(cls, prd_kps, batch, alpha), batch['src_kps'] should be changed to batch['trg_kps']

Could you verify whether this is right?

Thank you.

**Comment by SunghwanHong** [comment]
I believe that may be the case.

Many times when the results were strangely bad, I first try to swap the trg and src.

**Comment by JunbongJang** [comment]
Ok, thank you. 
Could you provide training hyperparameters, such as batch size and training epochs?

**Comment by SunghwanHong** [comment]
I can't really remember the exact setting except for what is stated in the paper.
Apologies for the inconvenience. 

By the way, I updated the pretrained weights link.

**Comment by JunbongJang** [comment]
Ok, training hyperparameters are inside the "args.pkl" file in your updated link.
Thank you.
